### PR TITLE
Fix alignment on About page

### LINKED ISSUE #155: Enhance UI at About Page
Here at About page, the margin of this part is not good. I want to fix this issue.
ad

@yatulearn Plz assign this issue under gssoc-ext level-1 and hacktoberfest.

### PR DESCRIPTION
**Pull request by SurajPrakash24**
### Description
Enhanced the alignment of Contact Us part on About page which makes it more attractive.

Fixes #155 

### Screenshots
FixAboutPage

@yatulearn Plz accept it under gssoc-ext level1 and hacktoberfest

### CODE REVIEW

**Comment by yatulearn** [comment]
kindly make changes in the new about page

**Comment by SurajPrakash24** [comment]
> kindly make changes in the new about page

Should i create a new PR?

**Comment by SurajPrakash24** [comment]
@yatulearn  Please merge both the PRs #222 and #248

**Comment by SurajPrakash24** [comment]
@yatulearn Plz merge the PR

**Comment by yatulearn** [comment]
your pr will be merged soon

**Comment by SurajPrakash24** [comment]
@yatulearn plz review and merge the PR under gssoc-ext level 2 and hacktoberfest-accepted.

**Comment by SurajPrakash24** [comment]
@yatulearn Plz merge the PR under gssoc-ext level 2

**Comment by SurajPrakash24** [comment]
@yatulearn plz merge the PR

**Pull request merged**
