### PR TITLE
Update the about us page | Issue #46

### PR DESCRIPTION
**Pull request by Shariq2003**
## Description
I have made the changes, in which I updated the structure of the About Us section and its appearance, also I have made some fixes in the Enquiry Section regarding the bottom spacing, also updated the footer that have nearly no spaces in the footer section and miss-capitalize words in it.

#46 
## Video

https://github.com/user-attachments/assets/91f5c827-56e8-4cc3-ab61-f52aa32167cc

### CODE REVIEW

**Comment by yatulearn** [comment]
Good job

**Comment by yatulearn** [comment]
make it responsive for all devices it not

**Comment by Shariq2003** [comment]
Okay working on this, please also update the label of level, as for responsiveness it's a time-consuming task.

**Comment by Shariq2003** [comment]
> make it responsive for all devices it not

Okay working on this, please also update the label of level, as for responsiveness it's a time-consuming task or I can also raise another issue of responsive of about us page.

**Comment by Shariq2003** [comment]
> > make it responsive for all devices it not
> 
> Okay working on this, please also update the label of level, as for responsiveness it's a time-consuming task or I can also raise another issue of responsive of about us page.

Or you can merge this PR, and then I can work on their responsiveness.
It will help me to separate the task from that one issue and will be clear and concise.

**Comment by yatulearn** [comment]
I have increased the level, you can work on the same pr

**Comment by Shariq2003** [comment]
@yatulearn I have updated the Abous Us Page and Added Responsiveness in it.
Please close #46 

https://github.com/user-attachments/assets/18c64e5f-65b8-4a3e-9df8-43ce872baf66

**Comment by yatulearn** [comment]
you did a good job just fix the conflicts

**Comment by Shariq2003** [comment]
> you can close the pr and make the changes in the repo again as we've made changes in the code and repo then you can raise the new pr

okay sir,

**Comment by Shariq2003** [comment]
@yatulearn i have fixed all conflicts, please review

**Comment by yatulearn** [comment]
your pr has conflicts kindly resolve it

**Comment by yatulearn** [comment]
your PR has conflicts that need to be addressed. Please review and resolve any issues. After resolving them, you can proceed to create a pull request. It is essential to resolve these conflicts in the branch.

**Comment by Shariq2003** [comment]
> your PR has conflicts that need to be addressed. Please review and resolve any issues. After resolving them, you can proceed to create a pull request. It is essential to resolve these conflicts in the branch.

OKay sir, o start working on these conflicts

**Comment by Shariq2003** [comment]
@yatulearn i have raised a new PR, and closing this one.

**Pull request closed without merging**
