### PR TITLE
dashboard ui added

### PR DESCRIPTION
**Pull request by eshaalal**
Task1 
NavBar updated with dashboard button
Screenshot 2024-10-08 223047

Task 2 
Dashboard UI created
Screenshot 2024-10-08 223013

### CODE REVIEW

**Comment by eshaalal** [comment]
@yatulearn I have completed the Dashboard UI, please look into it and if any change is required let me know.
I would be very happy if you merge this with level 2 , hacktoberfest, gssoc-ext lebel

**Comment by yatulearn** [comment]
your pr has conflicts kindly resolve them

**Comment by eshaalal** [comment]
@yatulearn conflicts are now resolved you can check

**Comment by eshaalal** [comment]
@yatulearn conflicts are now resolved you can check

**Comment by yatulearn** [comment]
ok

**Comment by yatulearn** [comment]
integrate the dashboard page with database/backend

**Comment by eshaalal** [comment]
@yatulearn there is no existing database in your code, How can i connect it to database

**Comment by eshaalal** [comment]
@yatulearn Just merge the PR and assign me the appropriate label (Level 2). You can assign the backend work to another contributor who might be able to assist with that part.

**Comment by MastanSayyad** [comment]
@yatulearn Are you active on your Repo?

**Comment by MastanSayyad** [comment]
@yatulearn why closed this PR without proper context, the contributor is waiting from last week to get it merge!

**Pull request closed without merging**
