### PR TITLE
Add scroll to up button

### PR DESCRIPTION
**Pull request by shubhagarwal1**
Added button to scroll to the top on the home page 
Screenshot 2024-10-04 at 4 24 33 PM

@yatulearn Please approve my PR.

### CODE REVIEW

**Comment by yatulearn** [comment]
your pr has conflicts kindly resolve it

**Comment by yatulearn** [comment]
make the scroll up button for every pages

**Comment by shubhagarwal1** [comment]
> make the scroll up button for every pages

can i do this in next PR, please accept this PR

**Comment by shubhagarwal1** [comment]
have resolved confllicst please merge my branch
@yatulearn

**Comment by yatulearn** [comment]
there is no scroll up button in the website

**Comment by shubhagarwal1** [comment]
> there is no scroll up button in the website

oh my god how this happend dont know, the code is still there but why scroll is not working 
i am looking into the matter

**Pull request closed without merging**
