### PR TITLE
Added All Contributors' Profile Photos

### LINKED ISSUE #31: Adding All Contributors Profile Photos in Readme.md file
### **Issue Description**

 - It lacks Contributors Profiles in Readme.md
 - It should be Like the image that I have shared
 - Hey! @yatulearn I have already fixed it. Can you assign me this issue under GSSoC-Extd and Hacktoberfest so that I can raise a PR.

 - Little about me: I am an experienced contributor as I have successfully completed Hacktoberfest-2020, Hacktoberfest-2023 and GSSoC-2024.

 **I will add this type of Live Contributor Profile Photos in it**
image

### PR DESCRIPTION
**Pull request by say-het**
Thanks @yatulearn for assigning me this issue.

 - Fixed #31 

Please merge this PR.

### CODE REVIEW

**Comment by yatulearn** [comment]
Kindly attach the screenshot of the changes that you have made

**Comment by say-het** [comment]
image

**Comment by yatulearn** [comment]
we have many contributors kindly check and add all of them

**Comment by say-het** [comment]
They are automatically added, and it's LIVE.

**Comment by yatulearn** [comment]
> They are automatically added, and it's LIVE.

ok good job

**Pull request merged**
