### PR TITLE
Add Contact us to header section

### PR DESCRIPTION
**Pull request by rutikakengal**
#39 Fixed Contact us in Header section 
Screenshots
Screenshot 2024-10-03 104740
@yatulearn

### CODE REVIEW

**Comment by yatulearn** [comment]
Make it working and connect it with the database. Make it responsive.

**Comment by yatulearn** [comment]
resolve the conflicts

**Comment by yatulearn** [comment]
Error in website

**Comment by rutikakengal** [comment]
I create a new pr please see that in issue #163 and add gssoc-ext,hactoberfast accepted and level 2 .@yatulearn

**Pull request closed without merging**
