### PR TITLE
Updation of AboutUs Page with Responsiveness | Issue #46

### PR DESCRIPTION
**Pull request by Shariq2003**
@yatulearn I have updated the code, and fixes the conflicts.
Issue #46 Completed.

https://github.com/user-attachments/assets/a70969a4-d43b-481f-bf24-8a85d2746816

### CODE REVIEW

**Comment by Shariq2003** [comment]
@yatulearn 
image

**Comment by Shariq2003** [comment]
@yatulearn this issue is of level 2, do check please

**Comment by yatulearn** [comment]
good job

**Comment by Shariq2003** [comment]
> good job

@yatulearn Update the label

**Comment by Shariq2003** [comment]
@yatulearn please update the level for this PR, because you have already claimed to increase

**Comment by Shariq2003** [comment]
> good job

@yatulearn sir, you still have not increased the level of this PR, I as asking again and again because u have said that , make the about us page updation along with responsiveness, I will increase the level, but u have not till now.

**Comment by Shariq2003** [comment]
@yatulearn sir, you still have not increased the level of this PR, I am asking again and again because u have said that, to make the about us page updation along with responsiveness, I will increase the level, but u have not till now.

Reference : My previous PR : https://github.com/yatulearn/yatulearn/pull/68

**Comment by Shariq2003** [comment]
@MastanSayyad sir, please also review this PR and give the level as per the work, and also refer the above comments. and also linked issue.

**Comment by Shariq2003** [comment]
> @yatulearn sir, you still have not increased the level of this PR, I am asking this because u have said that, to make the about us page updation along with responsiveness, I will increase the level, but u have not till now.
> 
> Reference : My previous PR : #68 and also u have mentioned to increase the level in my PR #68

@MastanSayyad sir this one.
Do assign level as per my work.

**Comment by Shariq2003** [comment]
> updated to level 2

Thanks @MastanSayyad sir

**Pull request merged**
