### PR TITLE
Fixed the Footer section !! #2

### PR DESCRIPTION
**Pull request by rounakdey6**
Hello PA,
Fixed the Footer section !! #2
Add bootstrap framework in the footer section. 
Adding the screenshot here.
image

### CODE REVIEW

**Comment by Himanshuch8055** [comment]
@rounakdey6, There are conflicts in your PR, so please check and resolve any issues. The issues addressed in this PR have already been resolved in PR number #47.

**Comment by rounakdey6** [comment]
I'm not getting.
Can you please elaborate?

**Comment by rounakdey6** [comment]
@Himanshuch8055 conflicts will be resolved by PA right?

**Comment by yatulearn** [comment]
your PR has conflicts that need to be addressed. Please review and resolve any issues. After resolving them, you can proceed to create a pull request. It is essential to resolve these conflicts in the branch.

**Comment by yatulearn** [comment]
footer doesn't look good, make the changes

**Comment by rounakdey6** [comment]
Can I get one more day ?

**Comment by rounakdey6** [comment]
So this PR is not to be counted?@yatulearn

**Comment by yatulearn** [comment]
ok

**Comment by Himanshuch8055** [comment]
> So this PR is not to be counted?@yatulearn

We appreciate your efforts. We need to close this PR due to duplication. You can check new issues.

**Comment by Himanshuch8055** [comment]
@rounakdey6, This issue has already been resolved in PR #47, so we need to close this.

**Comment by rounakdey6** [comment]
Sir , how can i resolve branch conflicts ?

**Comment by rounakdey6** [comment]
@yatulearn please help me out

**Comment by yatulearn** [comment]
Make the changes again in the repository as we have made some changes in the code and repository after making the changes you can raise the pr

**Pull request closed without merging**
