### PR TITLE
scale buttons done , computer network image done,numpy notes upload done 

### PR DESCRIPTION
**Pull request by ritikm31**
resolve:#124
scaled the header headlines except questions papers and also scale the logo and doubts button on hovering.

### CODE REVIEW

**Comment by ritikm31** [comment]
numpy notes updated in software tool section #127

**Comment by ritikm31** [comment]
why my all resolved issues seen in a single pull request.

**Comment by yatulearn** [comment]
your pr has conflicts kindly resolve them

**Comment by ritikm31** [comment]
i resolved the conflicts but it doesn't updated ,i guess now you have to merge them.

**Comment by ritikm31** [comment]
resolved now all the conflicts.

**Comment by yatulearn** [comment]
your pr has conflicts kindly resolve them

**Comment by ritikm31** [comment]
hey can you reopen it please btw i've solved the conflicts then why you closed this

**Comment by ritikm31** [comment]
solved this all fixes in #442

**Pull request closed without merging**
