### PR TITLE
UI Revamp: Navigation Bar Styling and Content Box Enhancements

### PR DESCRIPTION
**Pull request by harshpareshbhaigosalya**
This update includes a comprehensive redesign of the navigation bar and content boxes to enhance visual appeal and functionality. Key improvements involve a transparent scrolling navigation bar, hover effects, add comments in index file and alignment fixes. Additionally, the content boxes now feature an updated font style, simplified headings, shadow effects, and a modern layout, maintaining theme consistency while making the UI more engaging.

This contribution reflects a more sophisticated UI transformation, demonstrating a keen eye for design and attention to detail. It’s a step forward in making the project more intuitive and user-friendly. Excited to continue contributing and exploring more advanced features! 😊

Happy to contribute more and looking forward to making further enhancements!

Screenshot 2024-10-03 084903

Screenshot 2024-10-03 084922

### CODE REVIEW

**Comment by yatulearn** [comment]
your PR has conflicts that need to be addressed. Please review and resolve any issues. After resolving them, you can proceed to create a pull request. It is essential to resolve these conflicts in the branch.

**Comment by yatulearn** [comment]
do not make the changes in header and make the website responsive

**Comment by harshpareshbhaigosalya** [comment]
Hey, @yatulearn I have resolved the conflicts, you can merge this PR now.

**Comment by yatulearn** [comment]
kindly make changes in the header as original one

**Pull request closed without merging**
