### PR TITLE
# Adding a Custom effect in Cursor 

### PR DESCRIPTION
**Pull request by AnujShrivastava01**
# Sucessfully added a custom cursor to improve User interaction

https://github.com/user-attachments/assets/5cad9bbf-12cb-4e09-8643-f54cebe1bc72

Please Merge the pull request.
Thankyou!

### CODE REVIEW

**Comment by yatulearn** [comment]
your PR has conflicts that need to be addressed. Please review and resolve any issues. After resolving them, you can proceed to create a pull request. It is essential to resolve these conflicts in the branch.

**Comment by yatulearn** [comment]
Kindly check the responsiveness of the website

**Comment by yatulearn** [comment]
your PR has conflicts that need to be addressed. Please review and resolve any issues. After resolving them, you can proceed to create a pull request. It is essential to resolve these conflicts in the branch.

**Comment by AnujShrivastava01** [comment]
@yatulearn 
I have resolved all the conflicts.
Also I crosschecked the responsiveness of website with cursor effect .
I request you to please assign me level3 or atleast level2 label and merge the pull request .
Thankyou !

**Comment by yatulearn** [comment]
there is no need of animated cursor

**Comment by AnujShrivastava01** [comment]
> there is no need of animated cursor

Ok , No problem but it would be better if you would have informed me this earlier rather than assigning issue to me .

**Pull request closed without merging**
