### PR TITLE
Enhance UI and Styling of Landing Page

### PR DESCRIPTION
**Pull request by vastavikadi**
#288 resolved.

**Enhancements in Brief:**
- Changed the UI and styling of the buttons on the landing page to make them more modern and engaging.
- Corrected the spelling mistakes.
- Improved the styling of the footer and navbar to ensure a cohesive design across the site.

**Sample ScreenShots:**
Screenshot 2024-10-11 180559
Screenshot 2024-10-11 180618
Screenshot 2024-10-11 180630

### CODE REVIEW

**Comment by vastavikadi** [comment]
@yatulearn finished with this

**Comment by vastavikadi** [comment]
@yatulearn it's done

**Comment by yatulearn** [comment]
use black white blue colours on the button

**Comment by vastavikadi** [comment]
> use black white blue colours on the button

I did but it looking kinda off with the theme of the whole landing page.

**Comment by vastavikadi** [comment]
> use black white blue colours on the button

The buttons are with animated gradients.

**Comment by yatulearn** [comment]
didn't like the orange colour

**Pull request closed without merging**
