### PR TITLE
#56 fixed Add Contact us

### PR DESCRIPTION
**Pull request by rutikakengal**
fixed #56 Add contact us to header section , 
Add gssoc-ext,hactoberfast accepted and level 2 
@yatulearn 
Screenrecording

https://github.com/user-attachments/assets/070d36d2-c933-47c4-9ddb-51a684e80a18

### CODE REVIEW

**Comment by yatulearn** [comment]
kindly make working contact us page as if user enters the data it should store at the backend i.e database. I m giving level 2.

**Comment by rutikakengal** [comment]
@yatulearn i know frontend technologies @yatulearn assign this only I am not learn about database

**Comment by yatulearn** [comment]
ok

**Comment by yatulearn** [comment]
you did a good job but I can't merge it. Thank you for your contribution.

**Comment by rutikakengal** [comment]
Add level 1 or merge the pr , I work on it @yatulearn

**Pull request closed without merging**
