### PR TITLE
solved issue #211

### PR DESCRIPTION
**Pull request by Devanshu1603**
Added a scroll to top button . @yatulearn  Please review the PR and merge it accordingly.

### CODE REVIEW

**Comment by yatulearn** [comment]
someone else has already been assigned to do this task, you can work on another issue. Thank you for showing interest.

**Comment by Devanshu1603** [comment]
@yatulearn  why didn't you merge my PR.

**Comment by Devanshu1603** [comment]
> someone else has already been assigned to do this task, you can work on another issue. Thank you for showing interest.

It's not fair you have to check before assigning me , i made several changes on it. it will be a waste of time

**Comment by Devanshu1603** [comment]
@yatulearn please reply.

**Pull request closed without merging**
