### PR TITLE
Add "scroll to top " button

### PR DESCRIPTION
**Pull request by rutikakengal**
added scroll to top button to every section of website 
Add gssoc-ext,hactoberfast accepted and level 
#55 issue solved

### CODE REVIEW

**Comment by rutikakengal** [comment]
@yatulearn

**Comment by yatulearn** [comment]
your pr has conflicts kindly resolve it

**Comment by yatulearn** [comment]
your PR has conflicts that need to be addressed. Please review and resolve any issues. After resolving them, you can proceed to create a pull request. It is essential to resolve these conflicts in the branch.

**Comment by yatulearn** [comment]
add this feature on home screen's card's content i.e web development, ai ml etc

**Comment by yatulearn** [comment]
your pr has conflicts kindly resolve them

**Comment by rutikakengal** [comment]
Resolved the conflicts @yatulearn

**Comment by yatulearn** [comment]
your pr has conflicts kindly resolve them

**Comment by rutikakengal** [comment]
This pr has no conflicts @yatu;earn
Screenshot 2024-10-12 152352

**Pull request closed without merging**
