### PR TITLE
Added the desired theme changes in all the pages.

### PR DESCRIPTION
**Pull request by kekubhai**
here how it Looks 
Screenshot 2024-10-04 111219

Screenshot 2024-10-04 110852

Screenshot 2024-10-04 110704

It resolves the issue #74 .
Please review it and merge it. 
Thanks

### CODE REVIEW

**Comment by yatulearn** [comment]
kindly make the changes in nav bar on home screen as the original one and highlight the theme changing icon and fix it to the right corner and enhance the text color, boxes, buttons visibility for the dark mode, make it responsive for all the devices. kindly make change again in the repo as we have made some changes in the repo which may raise conflicts

**Comment by kekubhai** [comment]
The changes I implement in the navbar are working well. The problems you mentioned are because it is overlapping  with the css files of each of the html files individually. The one who created those needs to make changes as you wish. 
I have no knowledge how to implement the responsive feature , you can create an issue for the same people will love to work on that. 
Also can you tell me how can I can make changes in my repo to remove conflicts as all my files will be erased. 

You can merge my PR and then apply the changes as the branch shows no conflict as of now

**Comment by yatulearn** [comment]
your pr has conflicts kindly resolve it

**Comment by yatulearn** [comment]
kindly make the changes in nav bar on home screen as the original one and highlight the theme changing icon and fix it to the right corner

**Comment by yatulearn** [comment]
> The changes I implement in the navbar are working well. The problems you mentioned are because it is overlapping with the css files of each of the html files individually. The one who created those needs to make changes as you wish. I have no knowledge how to implement the responsive feature , you can create an issue for the same people will love to work on that. Also can you tell me how can I can make changes in my repo to remove conflicts as all my files will be erased.
> 
> You can merge my PR and then apply the changes as the branch shows no conflict as of now

you should save all data, you can close this pr and make the desired changes in the repo again as we have made some changes in the code and repo then you can raise the pr again or if you can make the changes without closing the pr you can

**Comment by kekubhai** [comment]
Okay I have started to resolve the conflicts. Please bear with me if I have any doubt. 
Thanks

**Comment by kekubhai** [comment]
I am getting probelm to merge conflicts . I have decided to do so by creating a new PR .
Thanks I will report to you when I'm done

**Pull request closed without merging**
