### PR TITLE
Added Web dev Quiz #392

### PR DESCRIPTION
**Pull request by KapuluruBhuvaneswariVspdbct**
Changes made:
1.Added Quiz button to web development page
2.created Quizes page
3.Created 3 quiz cards with animations
4.created seperate quizes for each topic
5.Results are announced after submitting quiz

https://github.com/user-attachments/assets/e527336a-2f3c-42fd-9b9f-329cf20933c4

w1
qui

image

html

htmlres

css
cssres
js1

js

### CODE REVIEW

**Review by KapuluruBhuvaneswariVspdbct — COMMENTED** [review]
NOW Web dev Quizes are added

**Comment by KapuluruBhuvaneswariVspdbct** [comment]
sie please consider the work done by me and add level3 and add score sir

**Comment by yatulearn** [comment]
you did a great job but you should create a separate section of quiz in the nav bar

**Comment by KapuluruBhuvaneswariVspdbct** [comment]
Ok I will

**Comment by KapuluruBhuvaneswariVspdbct** [comment]
sir,its done 

image

**Comment by yatulearn** [comment]
kindly check the header on home page
and add the quiz section on every page's nav bar/header i.e home, notes, about, etc.

**Comment by KapuluruBhuvaneswariVspdbct** [comment]
@yatulearn made the changes

**Comment by KapuluruBhuvaneswariVspdbct** [comment]
its done sir @yatulearn

**Comment by KapuluruBhuvaneswariVspdbct** [comment]
@yatulearn please merge this pr

**Comment by KapuluruBhuvaneswariVspdbct** [comment]
@yatulearn please mege this pr

**Comment by KapuluruBhuvaneswariVspdbct** [comment]
@amanazads please merge this fast

**Pull request merged**
