### PR TITLE
Add Scroll to Top Button

### LINKED ISSUE #162: Want to add back to top button
I Want to add back to top button in your website which will helps to improve the user experience

### PR DESCRIPTION
**Pull request by UdaySharmaGitHub**
- Fix #162 
- Add Scroll to Top Button for the  main pages like
- Home Page
- Question Paper Page
- Notes  Page
- About Page

@yatulearn 
Please Accept the Pull Request under hactoberfest or hactoberfest2024

Overview

https://github.com/user-attachments/assets/2188c9b8-c572-4d6f-a061-3761a4194e9c

### CODE REVIEW

**Comment by yatulearn** [comment]
your pr has conflicts kindly resolve it

**Comment by yatulearn** [comment]
add scroll to top feature in home screen's card's content i.e web development, ai ml and ll

**Comment by yatulearn** [comment]
your pr has conflicts kindly resolve them

**Comment by UdaySharmaGitHub** [comment]
@yatulearn Resolve the conflict please check .

**Comment by UdaySharmaGitHub** [comment]
Fix #192 
- Please Accept PR

https://github.com/user-attachments/assets/8f494fa3-852a-444b-902f-e66b75fd5099

**Comment by yatulearn** [comment]
your pr has conflicts kindly resolve it

**Comment by UdaySharmaGitHub** [comment]
@yatulearn Resolve the conflict please check .

**Comment by yatulearn** [comment]
fix header

**Pull request closed without merging**
