### PR TITLE
Add Login and Signup Features issue No #108

### PR DESCRIPTION
**Pull request by Iamanujosh**
### Summary:
This pull request introduces the following updates:

Implemented login and signup functionality.
Integrated authentication with Firebase.
Added form validation for both login and signup pages.
### Changes:
**Login Page:**
Created a user-friendly login interface.
Integrated Firebase authentication for secure login.
**Signup Page:**
Designed a registration form.
Added validation to prevent invalid inputs.
**Backend Updates:**
Connected login and signup forms to the backend for authentication.
Configured Firebase settings for user management.
**Screenshots:**
Login Screen
image
Sign in with google for both login and signup
image
Sign in with github for both login and signup
image
Signup Page
image

**Testing:**
Manual testing of login and signup flows.
Verified input validation and Firebase authentication.
Cross-browser testing completed for compatibility.
**Future Work:**
Implement password reset functionality.
Add multi-factor authentication (MFA) support.

### CODE REVIEW

**Comment by Iamanujosh** [comment]
Okayy it was my mistake I need to add it on home page also , if you want you can check on url like "login.html" url and "signin.html"

I'll fix the issue asap!!!

**Comment by Iamanujosh** [comment]
Subject: PR Updated with Requested Changes

Hi @yatulearn ,

I've addressed the feedback and made the necessary changes. The following updates were made:

Fixed the login functionality issue by 
Updated the visibility of the login/signup/logout buttons as per the review.
Please review the updated changes at your convenience.
**Before Login**
image
image
**After Login**
image
Thanks!

**Comment by yatulearn** [comment]
kindly fix the header

**Comment by Iamanujosh** [comment]
Okayyy I'll do it

**Comment by yatulearn** [comment]
fix the header and other issues as well

**Comment by Iamanujosh** [comment]
I am on another pr for this issue cause my branch was having lot's of issues!!!

**Comment by Iamanujosh** [comment]
I did pr no. 328

**Pull request closed without merging**
