### PR TITLE
Multilingual Support to YatuLearn Application

### PR DESCRIPTION
**Pull request by IkkiOcean**
Closes : #227 
## Description

This PR integrates the Google Multilingual Translator into the YatuLearn application, allowing users to easily translate content into various languages. This enhancement aims to improve accessibility and user experience for a broader audience.

## Changes Made:

1.	Footer Language Selection Dropdown:
	•	Implemented a user-friendly dropdown menu in the footer for selecting the desired language.
	•	This dropdown allows users to easily switch languages without navigating away from their current page.
2.	Language Persistence via Cookies:
	•	Integrated cookie functionality to save the selected language preference using the googtrans cookie.
	•	The selected language is retained for one year, ensuring that users do not have to reselect their language upon returning to the site.
3.	Seamless Language Application:
	•	The selected language from the dropdown is applied to the Google Translate feature, enhancing the overall user experience.
	•	On page load, the application checks for the saved language cookie and automatically selects the appropriate option in the dropdown.

## Video

https://github.com/user-attachments/assets/77db8cd6-5caa-4da5-a5ef-13d8819b8a53

### CODE REVIEW

**Comment by yatulearn** [comment]
your pr has conflicts kindly fix them

**Comment by IkkiOcean** [comment]
> your pr has conflicts kindly fix them

fixed all the conflicts! and please mark it level 3, I had to edit multiple files for this features.

**Comment by IkkiOcean** [comment]
@yatulearn  didn't merged the Pr? Please do it before I get more conflicts. It will be helpful

**Comment by IkkiOcean** [comment]
@yatulearn please merge it soon. I have already solved merge conflicts twice. do it before I get any more

**Comment by yatulearn** [comment]
fix the question paper section

**Pull request closed without merging**
