### PR TITLE
Added  CSS and fixed Transitions

### PR DESCRIPTION
**Pull request by devanshar**
Added a scroll to top transition for the bottom home links , and gave a proper shape for privacy policy and fixed some transition
image

### CODE REVIEW

**Comment by yatulearn** [comment]
Kindly check it once again, I m not able see any changes that you have made

**Comment by devanshar** [comment]
Checked it ! changes are made in privacy policy page , kindly click on the privacy policy it was this before and fixed and added  some trasitions
image

**Comment by yatulearn** [comment]
Kindly make the changes again or deploy again as I m not able to see any changes.

**Comment by devanshar** [comment]
ok

**Comment by devanshar** [comment]
Please merge first then deploy

**Comment by yatulearn** [comment]
I am not able to merge to merge it. Kindly check the issue and resolve it.
Screenshot 2024-10-03 at 01 10 35

**Comment by yatulearn** [comment]
your PR has conflicts that need to be addressed. Please review and resolve any issues. After resolving them, you can proceed to create a pull request. It is essential to resolve these conflicts in the branch.

**Comment by rounakdey6** [comment]
Can I please work on it ?

**Comment by yatulearn** [comment]
> Can I please work on it ?

ok

**Comment by rounakdey6** [comment]
I will do it by today

**Comment by yatulearn** [comment]
ok

**Comment by rounakdey6** [comment]
image
@yatulearn does it look good? 
Items in lists are animated- they transition when hovered over, sliding to the right slightly  and changing the background color to a light blue .

**Pull request closed without merging**
