### PR TITLE
Added feedback page

### PR DESCRIPTION
**Pull request by Ankitha2130**
Completed #244

### CODE REVIEW

**Comment by yatulearn** [comment]
is it taking responses I mean as I have given the feedback have you received it

**Comment by Ankitha2130** [comment]
Yes you will receive . you have to change it to your mail id . I have given some random mail id.

**Comment by Ankitha2130** [comment]
> is it taking responses I mean as I have given the feedback have you received it
Yes you will receive . you have to change it to your mail id . I have given some random mail id.

**Comment by yatulearn** [comment]
ok give it the email id of yatu learn i.e yatulearn@gmail.com

**Comment by Ankitha2130** [comment]
I have given mail id of yaru learn please review it.

**Comment by yatulearn** [comment]
submit feedback button is not working

**Pull request closed without merging**
