### PR TITLE
Fix for Roadmap Button Functionality and Styling

### PR DESCRIPTION
**Pull request by TornovDutta**
# Description:
This update addresses a bug where the Roadmap button was not functioning correctly. The issue has been resolved, ensuring that the button operates as intended. Additionally, a new styling feature has been implemented: when the button is active, it will turn white with black text, providing a clear visual indication of its state. This improvement enhances the user experience by making the active button more distinguishable.

### CODE REVIEW

**Comment by TornovDutta** [comment]
This is PR of issuse #1

**Comment by TornovDutta** [comment]
I cann't lebals it. please help me to lebal it.
@amanazads

**Comment by amanazads** [comment]
It is showing some bugs in the code. The loading speed is also slow and the banner is not loading properly. Can you check it once and fix it ?

**Comment by TornovDutta** [comment]
I have fixed the bugs; please check them.

**Comment by amanazads** [comment]
Kindly check the nav bar/header. On scrolling up it doesn’t look like as it was earlier. Kindly check and fix it

**Comment by TornovDutta** [comment]
I've fixed the navigation bar. Please have a look, @amanazads .

**Comment by amanazads** [comment]
on home screen, (roadmap buttons section) put the buttons 3 on left side and three on right according to the original website

**Comment by yatulearn** [comment]
Increase some margin between cards, roadmap and footer in home screen

**Comment by TornovDutta** [comment]
@amanazads please check the website

**Comment by TornovDutta** [comment]
The issue I assigned as #1 has a level 2 priority. Please fix it accordingly.
@amanazads @yatulearn

**Comment by amanazads** [comment]
Issue has already been assigned as the level 2

**Comment by TornovDutta** [comment]
Is the code correct?
 @amanazads

**Comment by yatulearn** [comment]
Good Job

**Comment by yatulearn** [comment]
We will merge it very soon

**Comment by yatulearn** [comment]
maintain the margin between cards-roadmap and roadmap-footer

**Comment by TornovDutta** [comment]
> maintain the margin between cards-roadmap and roadmap-footer
Sorry, I didn't understand it. can you explain more about it.
@yatulearn

**Comment by TornovDutta** [comment]
Are you tell about this margin ?
Screenshot 2024-10-02 170440

@yatulearn

**Comment by yatulearn** [comment]
> Are you tell about this margin ? Screenshot 2024-10-02 170440
> 
> @yatulearn

Screenshot 2024-10-02 at 17 15 27

notice the black arrow, and set the margins equal upper and lower

**Comment by TornovDutta** [comment]
@yatulearn I fix the mergin of the rodmap div

**Comment by TornovDutta** [comment]
please check it out

**Comment by yatulearn** [comment]
Good Job. Thank You

**Comment by yatulearn** [comment]
I am not able to merge to merge it. Kindly check the issue and resolve it.

**Comment by yatulearn** [comment]
your PR has conflicts that need to be addressed. Please review and resolve any issues. After resolving them, you can proceed to create a pull request. It is essential to resolve these conflicts in the branch.

**Pull request closed without merging**
