### PR TITLE
solved issue #212

### PR DESCRIPTION
**Pull request by Devanshu1603**
Created a login and signup page with email verification and password matching, also add features that input field get cleared after  details  submission . @yatulearn  please review the PR and merge it accordingly.
Screenshot 2024-10-09 023405
Screenshot 2024-10-09 023358

### CODE REVIEW

**Comment by yatulearn** [comment]
make it a working login/signup page i.e it should receive and store data at the backend or link it with firebase I have given it level3 it you're not able to do that kindly tell me

**Comment by Devanshu1603** [comment]
yes , i can connect the firebase database to it. But how will i know that its working or not , saving information to the database or not , as i didn't have access to the firebase details.

**Comment by Devanshu1603** [comment]
@yatulearn  i am unable to add functionality  to the login and signup page . if y0u want to remove level3 tag please at least provide level 2 tag as creating login and signup page also took time . Looking forward to work with you .

**Comment by yatulearn** [comment]
ok

**Comment by Devanshu1603** [comment]
@yatulearn  please merge the PR.

**Comment by yatulearn** [comment]
> @yatulearn please merge the PR.

we are reviewing the pr will merge it soon if it fits the condition

**Pull request closed without merging**
