### PR TITLE
Addition of B2T | Issue #70

### PR DESCRIPTION
**Pull request by Shariq2003**
Completed #70 
 

https://github.com/user-attachments/assets/904a97b8-71ad-4e88-af07-dab02d6e6562

 Please review, and merge
 
 I have added BackToTop Button in all the pages, could u please increase the level of this issue for this PR.

### CODE REVIEW

**Comment by yatulearn** [comment]
your pr has conflicts kindly resolve them

**Comment by Shariq2003** [comment]
> your pr has conflicts kindly resolve them

wait let me remove

**Comment by Shariq2003** [comment]
@yatulearn please check now

**Comment by Shariq2003** [comment]
> your pr has conflicts kindly resolve them

Done, please review

**Comment by Shariq2003** [comment]
@yatulearn please review and merge

**Pull request merged**
