### PR TITLE
PR for [Enhancement] Adding subsections in Notes page - issue #19

### PR DESCRIPTION
**Pull request by SurajPrakash24**
I have created the subsections in notes page. These subsections are based on Branch, Subjects or Technology. We can add or modify it in future. The subsections are collapsible providing efficient user interface and beginner friendly.

I have attached the screenshots for reference.

Please accept it under gssoc-ext level-3 and hacktoberfest.

### CODE REVIEW

**Comment by yatulearn** [comment]
Check the footer of notes section, make the required changes. Rest you did a good job

**Comment by SurajPrakash24** [comment]
> Check the footer of notes section, make the required changes. Rest you did a good job

The footer part is fine. I have added the screenshot with only half of the footer visible.

Here i have attached the full screenshot of footer.
footer

**Comment by yatulearn** [comment]
> > Check the footer of notes section, make the required changes. Rest you did a good job
> 
> The footer part is fine. I have added the screenshot with only half of the footer visible.
> 
> Here i have attached the full screenshot of footer. footer

kindly check the home screen footer and make the changes in the footer of the notes sections

**Comment by yatulearn** [comment]
kindly make the changes the in the footer section ASAP

**Comment by SurajPrakash24** [comment]
I have done the changes. Should i make a new Pull request

**Comment by yatulearn** [comment]
ok

**Comment by SurajPrakash24** [comment]
This PR has been updated So You can merge this one. 
Please accept it under gssoc-ext level-3 and hacktoberfest.

**Pull request merged**
