### PR TITLE
update the about page

### PR DESCRIPTION
**Pull request by rounakdey6**
image
image

### CODE REVIEW

**Comment by rounakdey6** [comment]
i update the about page, please merge this .

**Comment by rounakdey6** [comment]
@yatulearn please check this out

**Comment by rounakdey6** [comment]
@yatulearn Please merge this issue, I have already updated it

**Comment by rounakdey6** [comment]
@yatulearn #129 please check this , and I solved the merge conflict issue, please merge this

**Comment by rounakdey6** [comment]
@yatulearn Sir , please merge this

**Comment by rounakdey6** [comment]
@yatulearn please merge this . I have solved the issue.

**Comment by rounakdey6** [comment]
Please Sir merge this issue #129 @yatulearn

**Comment by rounakdey6** [comment]
Please merge this issue @yatulearn please sir

**Comment by yatulearn** [comment]
I was busy somewhere so I didn't see you merge request as weekend and holidays please do not spam

**Comment by yatulearn** [comment]
there is no change in about section

**Comment by rounakdey6** [comment]
@yatulearn I did sir ,

**Comment by rounakdey6** [comment]
I will give it by today

**Comment by yatulearn** [comment]
we have updated the about page

**Pull request closed without merging**
