### PR TITLE
styled topic cards and added hover effect to topic cards

### PR DESCRIPTION
**Pull request by YooAshu**
issue #7 
image

### CODE REVIEW

**Comment by yatulearn** [comment]
Good Job. Thank You

**Comment by yatulearn** [comment]
Make it responsive for all devices.

**Comment by YooAshu** [comment]
Okay 👍

**Comment by Himanshuch8055** [comment]
@YooAshu, your PR has conflicts that need to be addressed. Please review and resolve any issues. After resolving them, you can proceed to create a pull request. It is essential to resolve these conflicts in the branch.

**Comment by yatulearn** [comment]
your PR has conflicts that need to be addressed. Please review and resolve any issues. After resolving them, you can proceed to create a pull request. It is essential to resolve these conflicts in the branch.

**Comment by YooAshu** [comment]
Okay I will make it responsive and solve the merge conflicts

**Comment by yatulearn** [comment]
your PR has conflicts that need to be addressed. Please review and resolve any issues. After resolving them, you can proceed to create a pull request. It is essential to resolve these conflicts in the branch.

**Comment by YooAshu** [comment]
@yatulearn please check the PR issue #7

**Comment by yatulearn** [comment]
your PR has conflicts that need to be addressed. Please review and resolve any issues. After resolving them, you can proceed to create a pull request. It is essential to resolve these conflicts in the branch.

**Comment by YooAshu** [comment]
@yatulearn @Himanshuch8055 please check the PR issue #7

**Comment by yatulearn** [comment]
it looks good

**Comment by YooAshu** [comment]
Thanx

**Pull request merged**
