### PR TITLE
added  rate me popup modal at footer 

### PR DESCRIPTION
**Pull request by ananyag309**
#282 

image
image

working video

https://github.com/user-attachments/assets/e3af05bd-d969-47ea-ba55-8c76b3a812ef

### CODE REVIEW

**Comment by ananyag309** [comment]
@yatulearn please check and merge

**Comment by ananyag309** [comment]
@yatulearn sir please review it i need to raise 1 more pr

**Comment by yatulearn** [comment]
we are looking into your pr will get merged soon

**Comment by ananyag309** [comment]
@yatulearn please merge it i have 1 more pr prending

**Comment by ananyag309** [comment]
@yatulearn its been a long time please merge it

**Comment by ananyag309** [comment]
@MastanSayyad please check into this once i have 1 more pr pending to raise and there is no response from project admin

**Comment by MastanSayyad** [comment]
@yatulearn can your merge this?

**Pull request merged**
