### PR TITLE
Addition of FAQs | Issue #88

### PR DESCRIPTION
**Pull request by Shariq2003**
Completed #88 

https://github.com/user-attachments/assets/f046f82a-59cc-4a3e-8357-a22456279e0e

@yatulearn please check, and merge

### CODE REVIEW

**Comment by Shariq2003** [comment]
@yatulearn review and merge this

**Comment by yatulearn** [comment]
your pr has conflicts kindly resolve them

**Comment by Shariq2003** [comment]
> your pr has conflicts kindly resolve them

I have resolve all of them, please review again and merge

**Comment by yatulearn** [comment]
add faqs just above the footer

**Comment by Shariq2003** [comment]
> add faqs just above the footer

done please review

**Comment by yatulearn** [comment]
We will review all the changes it may take some time due to holidays

**Comment by Shariq2003** [comment]
@yatulearn please review and merge this

**Pull request merged**
