### PR TITLE
Add chatbot to the website

### PR DESCRIPTION
**Pull request by rutikakengal**
This Chatbot is built using API key By applying your own api key This is generate and and give access to any questions like chatgpt Please label gssoc-ext , hactoberfest accepted, level . I worked hard  on it .@yatulearn

### CODE REVIEW

**Comment by rutikakengal** [comment]
screen recording 

https://github.com/user-attachments/assets/067ced76-76e8-48d9-b1ba-3836bea65441

**Comment by rutikakengal** [comment]
#11 fixed

**Comment by rutikakengal** [comment]
level 3

**Comment by yatulearn** [comment]
your PR has conflicts that need to be addressed. Please review and resolve any issues. After resolving them, you can proceed to create a pull request. It is essential to resolve these conflicts in the branch.

**Comment by yatulearn** [comment]
Make the bot working i.e it should answer the questions being asked. Make changes according to the original website there are errors kindly check it

**Comment by rutikakengal** [comment]
In the code we use your own API key then the bot answers the question

**Comment by rutikakengal** [comment]
I fix the original code @yatulearn

**Comment by yatulearn** [comment]
your PR has conflicts that need to be addressed. Please review and resolve any issues. After resolving them, you can proceed to create a pull request. It is essential to resolve these conflicts in the branch.

**Comment by rutikakengal** [comment]
Ok I done the resolve conflits, truly I not know the What is Resolve conflits as this is my first the contribution to open source

**Comment by yatulearn** [comment]
> Ok I done the resolve conflits, truly I not know the What is Resolve conflits as this is my first the contribution to open source

when there is something that holding the pr to merge it may be any type of error pages issue, code error then it is called as conflicts. Here it was asking to remove those conflicts that are coming to the pr

**Comment by rutikakengal** [comment]
Ok I am done or not

**Comment by yatulearn** [comment]
kindly close the pr and start another pr for this issue

**Comment by yatulearn** [comment]
your PR has conflicts that need to be addressed. Please review and resolve any issues. After resolving them, you can proceed to create a pull request. It is essential to resolve these conflicts in the branch.

**Comment by yatulearn** [comment]
add the same header and footer as home page and chat bot make it responsive for all devices

**Comment by yatulearn** [comment]
kindly resolve the conflicts

**Comment by yatulearn** [comment]
kindly check the code and make the changes there are so many errors and duplication

**Pull request closed without merging**
