### PR TITLE
improved footer section

### PR DESCRIPTION
**Pull request by sweta123761**
footer section has been improved and boxes are added in it

### CODE REVIEW

**Comment by sweta123761** [comment]
@yatulearn plz check it

**Comment by yatulearn** [comment]
Not looking good and also you have missed some content from the original footer. Color theme should be the same as the original one. Make few other changes to make it look like good.

**Comment by sweta123761** [comment]
now plz check i have improved its adaption to different screen layouts

**Comment by sweta123761** [comment]
@yatulearn plz check it now

**Comment by yatulearn** [comment]
Footer is not looking good.

**Comment by yatulearn** [comment]
Please check the original repo once again and make the changes in it

**Comment by Himanshuch8055** [comment]
@sweta123761, your PR has conflicts that must be resolved. Additionally, this issue has been addressed in PR #47. @yatulearn, You can close this PR.

**Comment by yatulearn** [comment]
your PR has conflicts that need to be addressed. Please review and resolve any issues. After resolving them, you can proceed to create a pull request. It is essential to resolve these conflicts in the branch.

**Comment by sweta123761** [comment]
Ok

**Pull request closed without merging**
