### PR TITLE
add chatbot fixed

### PR DESCRIPTION
**Pull request by rutikakengal**
#64 issue fixed Added mini chatbot which access to any question and give quike response 
Addgssoc-ext,hactoberfast accepted and level 3 label to this pr @yatulearn fixed this issue 

screenrecording

https://github.com/user-attachments/assets/fff46b6f-febe-483e-8dfb-dea3987f2856

### CODE REVIEW

**Comment by yatulearn** [comment]
add the chatbot on every page rest you did a good job

**Comment by rutikakengal** [comment]
I am updated the Add mini chatbot @yatulearn

**Comment by yatulearn** [comment]
your pr has conflicts kindly resolve them

**Comment by yatulearn** [comment]
your pr has conflicts kindly resolve them

**Pull request closed without merging**
