### PR TITLE
Enhanced the UI of Pop up on hovering question paper item in navbar

### PR DESCRIPTION
**Pull request by govindumeesala**
Fixes issue #42 
# Improvements:
## Background & Borders:
 A light background (#f0f0f0) and soft shadow provide a cleaner look, while rounded corners make it more modern.
## Headings: 
A border under each heading with a little extra space creates better visual separation between sections (CSE, IT, ECE, MECH).
## Link Hover Effects:
 Adding hover effects to links enhances the interactivity, making the user experience smoother.
## Spacing & Layout:
 The flex-direction:
 column in the .links container ensures proper stacking of the links, while gap: 10px adds breathing space between them.
## Alignment:
 Aligning text to the left with sufficient padding helps improve readability.
This will give your dropdown a more user-friendly appearance.

image
@yatulearn please check once consider merging this pr

### CODE REVIEW

**Comment by yatulearn** [comment]
make it responsive for all the devices

**Comment by govindumeesala** [comment]
@yatulearn  ok

**Comment by govindumeesala** [comment]
@yatulearn Heyy made popup responsvie for for all screen sizes 
check once please

**Comment by yatulearn** [comment]
Fix the about page

**Comment by yatulearn** [comment]
> @yatulearn Heyy made popup responsvie for for all screen sizes check once please

hey there is no change in mobile phone

**Comment by govindumeesala** [comment]
@yatulearn working for mobile phone screen also 
here is the screenshot , please check once
image

**Pull request merged**
