### PR TITLE
Add Scroll to top button to the website

### PR DESCRIPTION
**Pull request by rutikakengal**
#41 issue fixed 

https://github.com/user-attachments/assets/0bd265e6-0e35-4422-a91c-548c206f0e07

### CODE REVIEW

**Comment by yatulearn** [comment]
Do it for all the sections i.e question paper, notes etc.

**Comment by yatulearn** [comment]
Kindly fix the footer and add the scroll to top button or every page

**Comment by yatulearn** [comment]
kindly fix the footer section and add the scroll up feature on every page

**Comment by rutikakengal** [comment]
I created new pr for this issue , I am new to gssoc open source contribution i am not understanding so i create new pr's for all my issue kindly check and review it and add gssoc-ext,hactoberfast accepted and level  @yatulearn

**Pull request closed without merging**
