### PR TITLE
Fixed back to home page button and logo

### PR DESCRIPTION
**Pull request by devanshar**
Fixed back to home page button and logo, before when we click on home button / logo at bottom it refresh the page now it will just scroll up back

### CODE REVIEW

**Comment by devanshar** [comment]
please assign me this under hactoberfest and gssoc-ext

**Comment by yatulearn** [comment]
resolve the conflicts

**Comment by devanshar** [comment]
> resolve the conflicts

Done

**Comment by yatulearn** [comment]
make the changes in the footer section

**Comment by devanshar** [comment]
> make the changes in the footer section

Done

**Pull request merged**
