### PR TITLE
Roadmap button hover effect fixed

### PR DESCRIPTION
**Pull request by DarshanchGIT**

### CODE REVIEW

**Comment by Himanshuch8055** [comment]
@DarshanchGIT, your PR has conflicts that need to be addressed. Please review and resolve any issues. After resolving them, you can proceed to create a pull request. It is essential to resolve these conflicts in the branch.

**Comment by yatulearn** [comment]
your PR has conflicts that need to be addressed. Please review and resolve any issues. After resolving them, you can proceed to create a pull request. It is essential to resolve these conflicts in the branch.

**Comment by yatulearn** [comment]
@Himanshuch8055 there is an issue on roadmap section i.e there is no change after on clicking the topic button of the roadmap, kindly check it on the main website and fix there issue is on the main website

**Comment by Himanshuch8055** [comment]
> @Himanshuch8055 there is an issue on roadmap section i.e there is no change after on clicking the topic button of the roadmap, kindly check it on the main website and fix there issue is on the main website

Alright, I will investigate and inform you of the issue.

**Pull request closed without merging**
