### PR TITLE
changes in about page 

### PR DESCRIPTION
**Pull request by rohitsharma2610**
i solved the problem #8. i have altered the font and added hover effect on cards and altered their width. Additionally i added some margin in address bar so it made the user-interface better. i also made some changes in the nav bar. i hope the changes helped your website. Kindly accept my pull request.

### CODE REVIEW

**Comment by yatulearn** [comment]
Kindly check the nav bar is should change color and stick after scrolling up

**Comment by rohitsharma2610** [comment]
you can check now.

**Comment by yatulearn** [comment]
Add one more card-
Position- CMO
Name- Sohail Alim
Linkedin- https://www.linkedin.com/in/sohail-alim-5b790a207/
Photo will be shares with you soon

**Comment by rohitsharma2610** [comment]
ok sure, and any other social link?

**Comment by rohitsharma2610** [comment]
all the cards should be in one line or i will put 4 cards in 2 lines so it will look good

**Comment by yatulearn** [comment]
> all the cards should be in one line or i will put 4 cards in 2 lines so it will look good

put it in two lines. makes changes in card color use another better than the color is used i.e sky blue try to make it look more good.

**Comment by yatulearn** [comment]
Sohail Alim
Here is the image for the CMO card

**Comment by rohitsharma2610** [comment]
Okay I will upload this, secondly I tried a lot of colors but the color palette of your website is blue so if I put any other color than blue, it looks too awkward.

**Comment by yatulearn** [comment]
Ok then no change in color

**Comment by rohitsharma2610** [comment]
okay, any other changes?

**Comment by yatulearn** [comment]
> okay, any other changes?

Currently no changes

**Comment by rohitsharma2610** [comment]
okay then let me commit the changes

**Comment by yatulearn** [comment]
Good Job. Thank You

**Comment by yatulearn** [comment]
I want if you can make some changes like in mobile devices, cards should scroll from right to left. I have attached a file you can take reference from that. 

Uploading Screen Recording 2024-10-02 at 23.45.49 (1).mp4…

**Comment by yatulearn** [comment]
I am not able to merge to merge it. Kindly check the issue and resolve it. Before doing anything kindly check the repo clearly.
Screenshot 2024-10-03 at 01 10 35

**Comment by yatulearn** [comment]
your PR has conflicts that need to be addressed. Please review and resolve any issues. After resolving them, you can proceed to create a pull request. It is essential to resolve these conflicts in the branch.

**Comment by rohitsharma2610** [comment]
Okay I'll do.

**Comment by rohitsharma2610** [comment]
hey, I'm sorry I mistakenly clicked the "unassign me" button so can you please assgin me again.

**Comment by yatulearn** [comment]
your PR has conflicts that need to be addressed. Please review and resolve any issues. After resolving them, you can proceed to create a pull request. It is essential to resolve these conflicts in the branch.

**Comment by rohitsharma2610** [comment]
can you send me the video of example.

**Comment by yatulearn** [comment]
your PR has conflicts that need to be addressed. Please review and resolve any issues. After resolving them, you can proceed to create a pull request. It is essential to resolve these conflicts in the branch.

**Comment by yatulearn** [comment]
Kindly close the pr make then changes in the repo again as we have made some changes in the original code and in repository then make the pr

**Comment by rohitsharma2610** [comment]
Sir, These are the changes I have made, you have to select which one you want, choose the file which one you want 'changed file or existing file' and them merge it

**Comment by yatulearn** [comment]
your pr has conflicts kindly resolve it

**Comment by yatulearn** [comment]
you can close the pr and make the changes in the repo again as we've made changes in the code and repo then you can raise the new pr

**Comment by rohitsharma2610** [comment]
can you give me write access then I can solve the conflicts in the PR.

**Comment by yatulearn** [comment]
you can close the pr and make the changes in the repo again as we've made changes in the code and repo then you can raise the new pr

**Comment by rohitsharma2610** [comment]
sir, i have made some changes in my forked reop so now you have to decide which code you want, these is a option "resolve conflicts" click on that anc choose the file you want.

**Comment by yatulearn** [comment]
you have to close the pr and start again in the repo and raise a new pr as resolve conflicts option is not available

**Comment by rohitsharma2610** [comment]
okay

**Pull request closed without merging**
