### PR TITLE
Blog section added

### PR DESCRIPTION
**Pull request by adityajha2005**
I’ve added the blog section and will be adding more content in the future. I also linked the navbar to the blog sections on all the pages, and it's functioning correctly.

### CODE REVIEW

**Comment by yatulearn** [comment]
your pr has conflicts kindly resolve it.

**Comment by yatulearn** [comment]
use cards to show blogs after clicking the button blog description should appear

**Comment by adityajha2005** [comment]
> use cards to show blogs after clicking the button blog description should appear, don't forget to make it responsive

okay i'll do that

**Comment by yatulearn** [comment]
you have error in the code, header and make the changes that I told earlier i.e use cards to store blogs and make it responsive, kindly fix issue

**Comment by adityajha2005** [comment]
> you have error in the code, header and make the changes that I told earlier i.e use cards to store blogs and make it responsive, kindly fix issue

yeah sure i'll do that

**Comment by adityajha2005** [comment]
just check once , and lemme know if this is allright . then i'll complete it and add some effects aswell

**Comment by yatulearn** [comment]
fix the content inside the boxes and revolve the banner from the blogs section

**Comment by adityajha2005** [comment]
okay i'll fix the contest , and will also make sure that the banner revolves around blogs

**Comment by yatulearn** [comment]
fix the conflicts

**Comment by adityajha2005** [comment]
I am really sorry , got busy with the exams . I'll be free from 26th so by 28th i'll complete it

**Pull request closed without merging**
