### PR TITLE
Updation of Questions Papers UI | Issue #118

### PR DESCRIPTION
**Pull request by Shariq2003**
Completed #118 

https://github.com/user-attachments/assets/168965e8-212c-415b-924c-9460a851f239

@yatulearn please review and close issue #118 with the exact label of level that is proposed by you in the issue.

### CODE REVIEW

**Comment by Shariq2003** [comment]
@yatulearn review and merge this

**Comment by Shariq2003** [comment]
@yatulearn please review and merge

**Comment by Shariq2003** [comment]
@yatulearn please also review this

**Comment by yatulearn** [comment]
we are reviewing it will merge it if it fits the condition

**Comment by Shariq2003** [comment]
> we are reviewing it will merge it if it fits the condition

what conditions sir,
okay let me know if you want any changes

**Comment by Shariq2003** [comment]
@yatulearn please review and merge this

**Comment by NEGRAH-S** [comment]
@MastanSayyad , UI updation comes under level2, no new page created

**Comment by Shariq2003** [comment]
> @MastanSayyad , UI updation comes under level2, no new page created

But @NEGRAH-S sir, i have redesigned the whole page, along with responsiveness

**Comment by Hemu21** [comment]
@MastanSayyad

**Review by MastanSayyad — COMMENTED** [review]
Okay i'll leave this PR as Level 3 but @Shariq2003 You should always make a PR well documented about the changes you did, I can only see a video and codebase

image

When reviewing, we only see the codebase, so it would help if PRs had clear descriptions outlining what changes were made. This transparency would reduce the need for further questions and requests

**Comment by Shariq2003** [comment]
> Okay i'll leave this PR as Level 3 but @Shariq2003 You should always make a PR well documented about the changes you did, I can only see a video and codebase
> 
> image
> 
> When reviewing, we only see the codebase, so it would help if PRs had clear descriptions outlining what changes were made. This transparency would reduce the need for further questions and requests

Okay sir, I will update my all PR's descriptions that are not well-structured

**Pull request merged**
