### PR TITLE
ADDED THE LOGIN PAGE

### PR DESCRIPTION
**Pull request by RitikSinha04**
CHANGES MADE PLEASE HAVE A LOOK 
https://github.com/user-attachments/assets/bec796c2-402a-425c-adfb-b7d5e0300132
ISSUE #217

### CODE REVIEW

**Comment by yatulearn** [comment]
make it a working login/signup page i.e it should receive and store data at the backend or link it with firebase I have given it level3 it you're not able to do that kindly tell me

**Comment by RitikSinha04** [comment]
ok i'll add the database too

**Comment by yatulearn** [comment]
ok

**Comment by RitikSinha04** [comment]
I am not able to add database. Can you please give me atleast level 2

**Pull request closed without merging**
