### PR TITLE
[Major Update] Organize Folder Structure (Merge this issue first) 🚀

### PR DESCRIPTION
**Pull request by Himanshuch8055**
This PR is the merge update to organize the folder structure of the repository. Issue no. #12

This PR reorganizes the folder structure of the project, as referenced in issue #12. The updated structure is shown in the attached image.
image

Merging this update is crucial as it will help streamline the management of future issues and improve overall project organization.

Kindly review and approve this PR to proceed with addressing the upcoming tasks more efficiently. Your need to merge this pull request before we can address all the upcoming issues and manage them together.

**This is the local output.**
image

**This is the privacy page changes.**
image

**I also updated the README.md file.**
image

### CODE REVIEW

**Comment by yatulearn** [comment]
Kindly check and add explore button on home page banner and make it responsive asap.

**Comment by Charul00** [comment]
now in this i also was implemented login and signup functionalities so that assigned to me i can make proper file strucutre

**Comment by Himanshuch8055** [comment]
@Charul00, this pull request is Merged. Please review any new issues and work on them.

**Comment by Himanshuch8055** [comment]
> Kindly check and add explore button on home page banner and make it responsive asap.

Yes, I will see no worries.

**Pull request merged**
