### PR TITLE
Fix for Roadmap Button Functionality and Styling 

### PR DESCRIPTION
**Pull request by TornovDutta**
# Description:
This update addresses a bug where the Roadmap button was not functioning correctly. The issue has been resolved, ensuring that the button operates as intended. Additionally, a new styling feature has been implemented: when the button is active, it will turn white with black text, providing a clear visual indication of its state. This improvement enhances the user experience by making the active button more distinguishable.

This is PR of issuse #1

### CODE REVIEW

**Comment by Himanshuch8055** [comment]
@TornovDutta, There are conflicts in your pull request. Please review and resolve any issues. Once resolved, you may create the pull request. First, resolve the conflicts and then resubmit the pull request.

**Comment by yatulearn** [comment]
There are conflicts in your pull request. Please review and resolve any issues. Once resolved, you may create the pull request. First, resolve the conflicts and then resubmit the pull request.

**Comment by yatulearn** [comment]
Why did you close the pr ?

**Comment by TornovDutta** [comment]
@yatulearn, this change had multiple conflicts that made the code messy, so I made a new PR.

**Pull request closed without merging**
