### PR TITLE
89 redesign question paper section

### PR DESCRIPTION
**Pull request by achintyasrivastav**
Redesigned the entire UI. Also it is responsive too! Here are the changes : 
Before : 
Screenshot 2024-10-04 015120

After (Full - View) : 
Screenshot 2024-10-10 232003
Screenshot 2024-10-10 232017
Screenshot 2024-10-10 232039
Screenshot 2024-10-10 232058

After (Mobile-View) : 
Screenshot 2024-10-10 232135
Screenshot 2024-10-10 232148
Screenshot 2024-10-10 232200
Screenshot 2024-10-10 232219

### CODE REVIEW

**Comment by yatulearn** [comment]
your pr has conflicts kindly resolve them

**Comment by yatulearn** [comment]
it is not looking good

**Comment by achintyasrivastav** [comment]
> it is not looking good
Do you want me to change the design again?

**Comment by achintyasrivastav** [comment]
Any update regarding issues, if there's still any let me know!!!

**Comment by yatulearn** [comment]
no need to make changes older one is good, sorry for the inconveniences caused. Thank you for showing interest.

**Pull request closed without merging**
