### PR TITLE
Change in yatu_learn_notes.html,added e-Resources.html,e-Resources.css

### PR DESCRIPTION
**Pull request by AyutheCoder**
I had added e-Resources subsection in notes section which further displays some e-books with their clickable links and some youtube playlist links also.Kindly review and accept the changes.

https://github.com/user-attachments/assets/193fcef0-ac42-4fa4-9810-b25440be3e98

### CODE REVIEW

**Comment by AyutheCoder** [comment]
@yatulearn Kindly review the changes made and accept it.

**Comment by AyutheCoder** [comment]
@yatulearn ,Kindly review the changes made.

**Comment by yatulearn** [comment]
not looking good use theme based color i.e black, blue, white n grey

**Comment by AyutheCoder** [comment]
OK

**Comment by AyutheCoder** [comment]
@yatulearn ,I had made the changes,kindly review and accept it.

https://github.com/user-attachments/assets/e7008819-ea1e-4432-ac98-4e041accb017

**Comment by AyutheCoder** [comment]
@yatulearn kindly review the changes and merge it.

**Comment by yatulearn** [comment]
you can put these e-resources in the particular topic's section i.e if the resource is related to web dev then put it inside it and if related to any technology put it insite technology section in notes section

**Comment by AyutheCoder** [comment]
@yatulearn Kindly merge the changes made.

**Pull request closed without merging**
