### PR TITLE
Improvement of NavBar

### PR DESCRIPTION
**Pull request by zakie2003**
Here is your requested Changes 
Screenshot 2024-10-03 181230

### CODE REVIEW

**Comment by yatulearn** [comment]
make the website responsive

**Comment by zakie2003** [comment]
> add this feature to all pages and make the website responsive

I didnt understand what you want, i did that thing on other pages too except the dark theme as to match the theme of that page as given below in picture.

Screenshot 2024-10-03 191107

**Comment by yatulearn** [comment]
It doesn't look make something unique and attractive

**Comment by yatulearn** [comment]
resolve the conflicts

**Pull request closed without merging**
